# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ncywa

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b833dc458cd04adfbefd6bfe1e4fa13a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2c3814a6b4e84c86898792d2d1ed4dbb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_b833dc458cd04adfbefd6bfe1e4fa13a }}/netcyabc/az-rwweb2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ncywa'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1523908efd8f4577872e1f25904ad123 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_b833dc458cd04adfbefd6bfe1e4fa13a }}/netcyabc/az-rwweb2:${{ github.sha }}'